const NOTES=['Do','Do#','Re','Re#','Mi','Fa','Fa#','Sol','Sol#','La','La#','Si'];
const CIRCLE=['Do','Sol','Re','La','Mi','Si','Fa#','Do#','Sol#','Re#','La#','Fa'];
const MAJOR=[0,2,4,5,7,9,11]; const MINOR_NAT=[0,2,3,5,7,8,10]; const MINOR_HAR=[0,2,3,5,7,8,11];
const ROM_MAJOR=['I','ii','iii','IV','V','vi','vii°']; const ROM_MINOR=['i','ii°','III','iv','V','VI','vii°'];
const QUALITY_MAJOR=['','m','m','','','m','dim']; const QUALITY_MINOR=['m','dim','','m','','','dim'];
const PROGS=[['Pop clásico','I V vi IV'],['Balada','I vi IV V'],['Rock','I IV V'],['Jazz básico','ii V I'],['Menor épica','i VI III VII'],['Andaluza','i VII VI V']];
let audioCtx=null, oscillators=[], metroTimer=null, beat=0, deferredInstall=null, tunerStream=null, tunerRAF=null, hiddenAnswer='';
const $=id=>document.getElementById(id); const idx=n=>NOTES.indexOf(n); const mod=n=>(n%12+12)%12; const noteAt=(root,semitone)=>NOTES[mod(idx(root)+semitone)];
function getScale(){const root=$('tonalidad').value, modo=$('modo').value, tipo=$('menorTipo').value; const ints=modo==='mayor'?MAJOR:(tipo==='armonica'?MINOR_HAR:MINOR_NAT); return ints.map(i=>noteAt(root,i));}
function getRoman(){return $('modo').value==='mayor'?ROM_MAJOR:ROM_MINOR} function getQuality(){return $('modo').value==='mayor'?QUALITY_MAJOR:QUALITY_MINOR}
function chordName(root,quality){return root+(quality==='dim'?'°':quality)}
function init(){CIRCLE.forEach(n=>{let o=document.createElement('option');o.value=n;o.textContent=n;$('tonalidad').appendChild(o)}); bind(); renderAll();}
function bind(){['modo','tonalidad','menorTipo','instrumento','trastes'].forEach(id=>$(id).addEventListener('input',renderAll));$('btnPlayScale').onclick=()=>playSequence(getScale().map(n=>freq(n,4)),.38);$('btnPlayChords').onclick=()=>playChordsSequence(buildDiatonicChords().map(c=>c.notes));$('btnPlayRoot').onclick=()=>playNote(freq($('tonalidad').value,4),.7);$('btnStopAudio').onclick=stopAudio;$('btnConstruir').onclick=buildProgression;$('btnPlayProg').onclick=playCurrentProgression;$('bpm').oninput=e=>{$('bpmLabel').textContent=e.target.value};$('compas').oninput=renderBeats;$('btnMetro').onclick=toggleMetro;$('btnTuner').onclick=toggleTuner;$('btnRandomNote').onclick=randomNote;$('btnRandomChord').onclick=randomChord;$('btnReveal').onclick=()=>{$('earResult').classList.remove('locked');$('earResult').textContent=hiddenAnswer||'Sin respuesta pendiente.'};$('btnClearNotes').onclick=clearPickedNotes;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('btnInstall').classList.remove('hidden')});$('btnInstall').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();deferredInstall=null;$('btnInstall').classList.add('hidden')}};}
function renderAll(){ $('menorTipoWrap').classList.toggle('hidden',$('modo').value!=='menor'); renderTitle(); renderCircle(); renderKeyboard(); renderInfo(); renderChords(); renderProgressions(); buildProgression(); renderFretboard(); renderBeats(); renderNotePicker(); }
function renderTitle(){const root=$('tonalidad').value, modo=$('modo').value, tipo=$('menorTipo').value; $('tituloTonalidad').textContent=`${root} ${modo==='mayor'?'Mayor':'Menor '+(tipo==='armonica'?'armónica':'natural')}`; const s=getScale(); $('resumenTonalidad').textContent=`Notas: ${s.join(' - ')}. Usa esta vista para estudiar teclado, acordes, progresiones y diapasón.`; $('chipsNotas').innerHTML=s.map((n,i)=>`<span class="chip ${i===0?'root':''}">${i+1}. ${n}</span>`).join('');}
function renderCircle(){const svg=$('circuloSvg');svg.innerHTML='';const R=128;CIRCLE.forEach((n,i)=>{const a=(i/12)*Math.PI*2-Math.PI/2;const x=Math.cos(a)*R,y=Math.sin(a)*R;const active=n===$('tonalidad').value;svg.insertAdjacentHTML('beforeend',`<g class="circle-note ${active?'circle-active':''}" data-note="${n}"><circle cx="${x}" cy="${y}" r="28" fill="${active?'#21d4a3':'#1b2130'}" stroke="#5c6680" stroke-width="2"/><text x="${x}" y="${y+4}" text-anchor="middle" class="circle-text" fill="${active?'#07110e':'#f5f7fb'}">${n}</text><text x="${x}" y="${y+19}" text-anchor="middle" class="circle-degree">${i===0?'0':i<=6?'+'+i:i-12}</text></g>`)});svg.insertAdjacentHTML('beforeend','<circle cx="0" cy="0" r="68" fill="rgba(124,92,255,.18)" stroke="#7c5cff"/><text x="0" y="-5" text-anchor="middle" fill="#fff" font-size="16" font-weight="900">Círculo</text><text x="0" y="16" text-anchor="middle" fill="#aab2c5" font-size="12">de quintas</text>');svg.querySelectorAll('.circle-note').forEach(g=>g.onclick=()=>{$('tonalidad').value=g.dataset.note;renderAll()});}
function renderKeyboard(){const WHITE=['Do','Re','Mi','Fa','Sol','La','Si'];const scale=getScale(),root=$('tonalidad').value;let html='';for(let oct=3;oct<=5;oct++){WHITE.forEach(n=>{html+=keyHtml(n,oct,false,scale,root); if(!['Mi','Si'].includes(n)) html+=keyHtml(n+'#',oct,true,scale,root);});}$('teclado').innerHTML=html;document.querySelectorAll('.key').forEach(k=>k.onclick=()=>playNote(freq(k.dataset.note,Number(k.dataset.oct)),.45));}
function keyHtml(n,oct,black,scale,root){return `<div class="key ${black?'black':'white'} ${scale.includes(n)?'in-scale':''} ${n===root?'root':''}" data-note="${n}" data-oct="${oct}">${n}</div>`}
function renderInfo(){const s=getScale(), rel=$('modo').value==='mayor'?noteAt($('tonalidad').value,9):noteAt($('tonalidad').value,3);const fifth=noteAt($('tonalidad').value,7), fourth=noteAt($('tonalidad').value,5);$('infoRapida').innerHTML=[['Tónica',$('tonalidad').value],['Relativa',rel],['Quinta',fifth],['Cuarta',fourth],['Escala',s.join(' - ')],['Uso sugerido',$('modo').value==='mayor'?'Pop, rock, worship, balada':'Rock, metal, regional, tensión']].map(x=>`<div class="info-box"><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join('');}
function buildDiatonicChords(){const scale=getScale(), rom=getRoman(), qual=getQuality();return scale.map((n,i)=>{const notes=[scale[i],scale[(i+2)%7],scale[(i+4)%7]];return{degree:rom[i],name:chordName(n,qual[i]),notes}})}
function renderChords(){const chords=buildDiatonicChords();$('acordes').innerHTML=chords.map(c=>`<button class="chord-card" data-notes="${c.notes.join(',')}"><span class="degree">${c.degree}</span><strong>${c.name}</strong><small>${c.notes.join(' - ')}</small></button>`).join('');document.querySelectorAll('.chord-card').forEach(b=>b.onclick=()=>playChord(b.dataset.notes.split(',')));}
function renderProgressions(){$('progresiones').innerHTML=PROGS.map(p=>`<button class="prog-card" data-prog="${p[1]}"><strong>${p[0]}</strong><span>${p[1]}</span></button>`).join('');document.querySelectorAll('.prog-card').forEach(b=>{b.onclick=()=>{$('progresionInput').value=b.dataset.prog;buildProgression();}})}
function buildProgression(){const chords=buildDiatonicChords(), map={};chords.forEach(c=>map[c.degree.toLowerCase().replace('°','')]=c);const tokens=$('progresionInput').value.replaceAll('-',' ').split(/\s+/).filter(Boolean);const found=tokens.map(t=>map[t.toLowerCase().replace('°','')]).filter(Boolean);$('progresionResultado').innerHTML=found.length?found.map(c=>`<span class="badge"><b>${c.degree}</b> ${c.name}</span>`).join(''):'No se reconoció la progresión.';return found;}
function playCurrentProgression(){playChordsSequence(buildProgression().map(c=>c.notes));}
function renderFretboard(){const frets=Number($('trastes').value), inst=$('instrumento').value; const tuning=inst==='bajo4'?[['Sol',3],['Re',3],['La',2],['Mi',2]]:[['Mi',4],['Si',3],['Sol',3],['Re',3],['La',2],['Mi',2]];const scale=getScale(), root=$('tonalidad').value;let html=`<div style="--frets:${frets+1}">`;tuning.forEach(([open,oct])=>{html+=`<div class="string-row"><div class="string-label">${open}</div>`;for(let f=0;f<=frets;f++){const n=NOTES[mod(idx(open)+f)];html+=`<div class="fret"><span class="note-dot ${scale.includes(n)?'in-scale':''} ${n===root?'root':''}" data-note="${n}" data-oct="${oct+Math.floor((idx(open)+f)/12)}">${n}</span></div>`}html+='</div>'});html+='</div>';$('fretboard').innerHTML=html;document.querySelectorAll('.note-dot').forEach(d=>d.onclick=()=>playNote(freq(d.dataset.note,Number(d.dataset.oct)),.35));}
function renderBeats(){const c=Number($('compas').value);$('beatLights').innerHTML=Array.from({length:c},(_,i)=>`<span class="beat" data-i="${i}"></span>`).join('');}
function toggleMetro(){if(metroTimer){clearInterval(metroTimer);metroTimer=null;$('btnMetro').textContent='Iniciar';document.querySelectorAll('.beat').forEach(b=>b.classList.remove('on'));return} beat=0;$('btnMetro').textContent='Detener';metroTick();metroTimer=setInterval(metroTick,60000/Number($('bpm').value));}
function metroTick(){const c=Number($('compas').value);document.querySelectorAll('.beat').forEach((b,i)=>b.classList.toggle('on',i===beat));clickSound(beat===0?880:520);beat=(beat+1)%c;if(metroTimer){clearInterval(metroTimer);metroTimer=setInterval(metroTick,60000/Number($('bpm').value));}}
function ctx(){if(!audioCtx)audioCtx=new (window.AudioContext||window.webkitAudioContext)();return audioCtx} function stopAudio(){oscillators.forEach(o=>{try{o.stop()}catch(e){}});oscillators=[]}
function freq(n,oct=4){return 440*Math.pow(2,((idx(n)-idx('La'))+(oct-4)*12)/12)}
function playNote(f,d=.5,type='sine'){const c=ctx(),o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(.18,c.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+d);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+d+.04);oscillators.push(o)}
function playChord(notes){notes.forEach((n,i)=>playNote(freq(n,4+(i>1?1:0)),.9,'triangle'))} function playSequence(fs,d){fs.forEach((f,i)=>setTimeout(()=>playNote(f,d),i*d*1000))} function playChordsSequence(chords){chords.forEach((ns,i)=>setTimeout(()=>playChord(ns),i*950))} function clickSound(f){playNote(f,.065,'square')}
function renderNotePicker(){if($('notePicker').children.length)return; $('notePicker').innerHTML=NOTES.map(n=>`<button class="note-btn" data-note="${n}">${n}</button>`).join('');document.querySelectorAll('.note-btn').forEach(b=>b.onclick=()=>{b.classList.toggle('selected');detectChord()});}
function clearPickedNotes(){document.querySelectorAll('.note-btn').forEach(b=>b.classList.remove('selected'));detectChord()} function detectChord(){const picked=[...document.querySelectorAll('.note-btn.selected')].map(b=>b.dataset.note); if(picked.length<2){$('chordFinderResult').textContent='Selecciona 2 o más notas.';return} const pcs=picked.map(idx).sort((a,b)=>a-b); const patterns={'Mayor':[0,4,7],'Menor':[0,3,7],'Disminuido':[0,3,6],'Aumentado':[0,4,8],'7':[0,4,7,10],'maj7':[0,4,7,11],'m7':[0,3,7,10]};let out=[];NOTES.forEach(root=>{const r=idx(root);const rel=pcs.map(p=>mod(p-r)).sort((a,b)=>a-b);Object.entries(patterns).forEach(([name,pat])=>{if(pat.every(x=>rel.includes(x))&&rel.length===pat.length)out.push(root+' '+name)})});$('chordFinderResult').innerHTML=out.length?`Posibles: <b>${out.join(', ')}</b>`:'No encontré un acorde básico exacto.';}
function randomNote(){const n=NOTES[Math.floor(Math.random()*NOTES.length)];hiddenAnswer='Respuesta: '+n;$('earResult').classList.add('locked');$('earResult').textContent=hiddenAnswer;playNote(freq(n,4),.8)}
function randomChord(){const c=buildDiatonicChords()[Math.floor(Math.random()*7)];hiddenAnswer=`Respuesta: ${c.degree} ${c.name} (${c.notes.join(' - ')})`;$('earResult').classList.add('locked');$('earResult').textContent=hiddenAnswer;playChord(c.notes)}
async function toggleTuner(){if(tunerStream){tunerStream.getTracks().forEach(t=>t.stop());tunerStream=null;cancelAnimationFrame(tunerRAF);$('btnTuner').textContent='Activar afinador';return} try{tunerStream=await navigator.mediaDevices.getUserMedia({audio:true});$('btnTuner').textContent='Detener afinador';startTuner(tunerStream)}catch(e){$('tunerCents').textContent='No se pudo activar el micrófono.'}}
function startTuner(stream){const c=ctx(),src=c.createMediaStreamSource(stream),an=c.createAnalyser();an.fftSize=2048;src.connect(an);const buf=new Float32Array(an.fftSize);function loop(){an.getFloatTimeDomainData(buf);const ac=autoCorrelate(buf,c.sampleRate);if(ac>0){const n=noteFromFreq(ac), cents=Math.round(1200*Math.log2(ac/freq(n.note,n.oct)));$('tunerNote').textContent=n.note;$('tunerHz').textContent=ac.toFixed(1)+' Hz';$('tunerCents').textContent=cents===0?'Afinado':(cents>0?`Alto +${cents} cents`:`Bajo ${cents} cents`)}tunerRAF=requestAnimationFrame(loop)}loop()}
function autoCorrelate(buf,sr){let rms=0;for(const v of buf)rms+=v*v;rms=Math.sqrt(rms/buf.length);if(rms<.01)return -1;let best=0,bestCorr=0;for(let off=20;off<1000;off++){let corr=0;for(let i=0;i<buf.length-off;i++)corr+=Math.abs(buf[i]-buf[i+off]);corr=1-corr/(buf.length-off);if(corr>bestCorr){bestCorr=corr;best=off}}return bestCorr>.9?sr/best:-1}
function noteFromFreq(f){const midi=Math.round(69+12*Math.log2(f/440));return{note:NOTES[mod(midi-60)],oct:Math.floor(midi/12)-1}}
init();